# Generated by Django 5.2.1 on 2025-05-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarianprofile',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='librarianprofile',
            name='employee_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
