# Generated by Django 5.0.6 on 2026-02-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_decouple_borrow_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='student',
        ),
    ]
