# Generated by Django 5.0.6 on 2026-02-10 01:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_borrow_student_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBookUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_id', models.CharField(blank=True, max_length=64, null=True)),
                ('borrower_username', models.CharField(blank=True, max_length=150, null=True)),
                ('file', models.FileField(upload_to='audio_books/%Y/%m/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='qr_code_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for QR codes. QR image generation and decoding are handled by OpenLibraryQRService.', unique=True, verbose_name='QR Code ID'),
        ),
    ]
