# Generated by Django 4.2.28 on 2026-02-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_borrow_shelf_book_nullable_and_book_fk'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_book_title_author'),
        ),
    ]
